version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependency:"
    labels:
      - "dependency"
    reviewers:
      - "Cyanic76"
